application: openalive
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: django
  version: "latest"
  
builtins:
- remote_api: on
- appstats: on
- deferred: on
- admin_redirect: on

admin_console:
  pages:
  - name: Category Admin
    url: /admin/category

handlers: 
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /google1c31f830f1d5b3e9.html
  static_files: static/google1c31f830f1d5b3e9.html
  upload: static/google1c31f830f1d5b3e9.html
 
- url: /admin/.*
  script: bootstrap.app
  login: admin
  
- url: /.*
  script: bootstrap.app
