application: openalive
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: django
  version: "latest"
- name: jinja2
  version: "latest"
  
builtins:
- remote_api: on
- appstats: on
- deferred: on
- admin_redirect: on

admin_console:
  pages:
  - name: Category Admin
    url: /admin/category

handlers: 
- url: /static
  static_dir: static
  secure: never

- url: /appengine_admin_media
  static_dir: lib/appengine_admin/media
  secure: never

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
 
- url: /admin/.*
  script: bootstrap.app
  login: admin
  
- url: /.*
  script: bootstrap.app
