application: openalive
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- remote_api: on
- appstats: on
- deferred: on
- admin_redirect: on 

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  
- url: /static
  static_dir: static
  secure: never

- url: /appengine_admin_media
  static_dir: lib/appengine_admin/media
  secure: never

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
 
- url: /admin/.*
  script: bootstrap.py
  login: admin
  
- url: /.*
  script: bootstrap.py
